import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class GameButtons extends JFrame {
    private ArrayList<JButton> buttons;
    private ArrayList<Integer> selectedIndices;

    public GameButtons(ArrayList<Integer> array) {
        setTitle("Ciparu izvele");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new FlowLayout());
        buttons = new ArrayList<>();
        selectedIndices = new ArrayList<>();
        createButtons(array);
        pack();
        setVisible(true);
    }

    private void createButtons(ArrayList<Integer> array) {
        for (Integer num : array) {
            JButton button = new JButton(num.toString());
            button.addActionListener(new ButtonClickListener(button));
            buttons.add(button);
            add(button);
        }
    }

    public void updateButtons(ArrayList<Integer> array) {
        for (JButton button : buttons) {
            remove(button);
        }
        buttons.clear();
        selectedIndices.clear();
        createButtons(array);
        revalidate();
        repaint();
    }
    public boolean check() {
        if (selectedIndices.size() != 2) {
            return false;
        }
        return Math.max(selectedIndices.get(0), selectedIndices.get(1)) - Math.min(selectedIndices.get(0), selectedIndices.get(1)) == 1;
    }
    // Generated by LLM(ChatGPT) Lai butu iespejams izveleties 2 ciparus
    private class ButtonClickListener implements ActionListener {
        private JButton button;

        public ButtonClickListener(JButton button) {
            this.button = button;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            int index = buttons.indexOf(button);

            if (selectedIndices.contains(index)) {
                selectedIndices.remove((Integer) index);
                button.setBackground(null);
            } else {
                if (selectedIndices.size() < 2) {
                    selectedIndices.add(index);
                    button.setBackground(Color.GREEN);
                }
            }
        }
    }
}
